config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#home"

  get 'restaurants/search', to: 'restaurants#search'
  resources :restaurants do
    resources :items
    get 'dishes', to: 'dishes#list', as: 'restaurant_dishes'
  end
  resources :items
  resources :dishes

end

app/models/dish.rb
class Dish < ApplicationRecord
    has_many :items, dependent: :delete_all
    validates :name, presence: true
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  load_and_authorize_resource
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
  end

  def list
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dishes = @restaurant.dishes
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully created." }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Dish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:name)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
    <h3>
      <%= dish.name %>
    </h3>

  </div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='card', style='width: 18rem;'>
        <div class='card-body'>
            <div class='mb-3'>
              <%= form.label :name, { class: "form-label"} %>
              <%= form.text_field :name, { class: "form-control", placeholder: "Name" } %>
            </div>

            <form>
                <input type="submit" value="Submit changes" class='btn btn-primary'>
            </form>
        <div>
    </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Show this dish", @dish, class:'btn btn-outline-info btn-sm' %> |
  <%= link_to "Back to dishes", dishes_path, class: 'btn btn-outline-dark btn-sm' %>
</div>

app/views/dishes/index.html.erb
  <p style="color: green"><%= notice %></p>
<div style='margin:1rem;'>
  <%= link_to '', root_path, class: 'btn btn-outline-dark fa-solid fa-arrow-left', style:'margin:1rem;'%>
</div>

<div class='text-center'>
  <h1>Dishes</h1>
</div>

<div class="container" style='width:35rem;'>
  <table class="table" style='margin:auto; width:30rem;'>
  <thead>
    <tr>
      <th scope='col'>Name</th>
    </tr>
  </thead>
    <tbody>
      <% @dishes.each do |dish| %>
        <tr>
          <td><%= dish.name%></td>
          <td><%= link_to "", dish, class: 'btn btn-outline-info btn-sm fa-solid fa-eye' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <br>
  <div style='margin-left:2rem;'>
  <%= link_to "", new_dish_path, class: 'btn btn-outline-secondary btn-sm fa-solid fa-plus' %>
  </div>

app/views/dishes/list.html.erb
<h3>Dishes for <%= @restaurant.name %></h3>
<ul>
  <% @dishes.each do |dish| %>
    <li><%= dish.name %></li>
  <% end %>
</ul>

app/views/dishes/new.html.erb
<div class='container'>
  <h1>New dish</h1>

  <%= render "form", dish: @dish %>

  <br>

  <div>
    <%= link_to "Back to dishes", dishes_path, class:'btn btn-outline-primary btn-sm' %>
  </div>
</div>

app/views/dishes/show.html.erb
<div class='container' style='margin-left: 3rem; margin-top:1rem; background-color: rgb(0 0 0/0%)'>
  <%= link_to "", dishes_path, class: "btn btn-outline-dark fa-solid fa-arrow-left" %>
</div>

<div class='container' style='width:25rem; margin:auto;'>

  <div class="card">
    <div class="card-header text-center" style='background-color:#adb5bd;'>
      <%= render @dish %>
    </div>
    <ul class="list-group list-group-flush">
      <% @dish.items.each do |item| %>
        <li class='list-group-item'><%= item.name %> </li>
      <% end %>
    </ul>
  </div>

  <br>
  <% if can? :manage, Dish %>
    <%= link_to "", edit_dish_path(@dish), class: 'btn btn-outline-warning fa-solid fa-pencil' %>
  <% end %>
      <br><br>
  <% if can? :manage, Dish %>
    <%= button_to "", @dish, method: :delete, class: 'btn btn-outline-danger fa-solid fa-trash'%>
  <% end %>
  </div>




</div>