config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#home"

  get 'restaurants/search', to: 'restaurants#search'
  resources :restaurants do
    resources :items
    get 'dishes', to: 'dishes#list', as: 'restaurant_dishes'
  end
  resources :items
  resources :dishes

end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :restaurant
    belongs_to :dish
    
    validates :name, presence: true
    validates :price, numericality: { greater_than: 0 }
    validates :callories, numericality: { greater_than: 0 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to restaurant_path(@item.restaurant_id), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :callories, :restaurant_id, :dish_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class='container'>
  <%= form_for ([:restaurant, item]) do |form| %>
    <% if @item.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% @item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='card'>
        <div class='card-body'>
            <div class='mb-3'>
            <%= form.label :name, { class: "form-label"} %>
            <%= form.text_field :name, { class: "form-control", placeholder: "Name" }%>
            </div>

            <div class='mb-3'>
            <%= form.label :price, { class: "form-label"} %>
            <%= form.number_field :price, { class: "form-control", placeholder: "Price" } %>
            </div>

            <div class='mb-3'>
            <%= form.label :callories, { class: "form-label"} %>
            <%= form.number_field :callories, { class: "form-control", placeholder: "Callories" } %>
            </div>

            <form>
                <input type="submit" value="Submit changes" class='btn btn-primary'>
            </form>
        </div>
    </div>
  <% end %>
</div>

app/views/items/_formnew.html.erb
<div class='container'>
  <%= form_for item do |form| %>
    <% if @item.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% @item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='card', style='width: 18rem;'>
        <div class='card-body'>
            <div class='mb-3'>
            <%= form.label :name, { class: "form-label"} %>
            <%= form.text_field :name, { class: "form-control", placeholder: "Name" }%>
            </div>

            <div class='mb-3'>
            <%= form.label :price, { class: "form-label"} %>
            <%= form.number_field :price, { class: "form-control", placeholder: "Price" } %>
            </div>

            <div class='mb-3'>
            <%= form.label :callories, { class: "form-label"} %>
            <%= form.number_field :callories, { class: "form-control", placeholder: "Callories" } %>
            </div>

            <div class='mb-3'>
              <%= form.label :restaurant_id, class: "form-label" %>
              <%= form.collection_select :restaurant_id, Restaurant.all, :id, :name, { include_blank: "Select a Restaurant" }, class: "form-control" %>
            </div>

            <div class='mb-3'>
              <%= form.label :dish_id, {class: "form-label"} %>
              <%= form.collection_select :dish_id, Dish.all, :id, :name, { include_blank: 'Select a Dish' }, class: "form-control" %>
            </div>

            <div>
                <%= form.submit "Create Item", class: "btn btn-primary" %>
            </div>
        </div>
    </div>
  <% end %>
</div>

app/views/items/_item.html.erb
<div class="card" style='width:25rem; margin:auto;'>
<div id="<%= dom_id item %>">
  <div class="card-header text-center" style='background-color:#adb5bd;'>
    <h3>
      <%= item.name %>
    </h3>
  </div>
  <div class="card-body">
  <p class=''>
    <strong>Price:</strong>
    $<%= item.price%>
    <br>
    <strong>Callories:</strong>
    <%= item.callories %>
  </p>
  </div>
</div>
</div>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing item</h1>

  <%= render "form", item: @item %>

  <br>

  <div>
    <%= link_to "Back to items",  restaurant_path(@item.restaurant_id), class: 'btn btn-primary' %>
  </div>
</div>

app/views/items/index.html.erb
<div style='margin:1rem;'>
  <%= link_to '', root_path, class: 'btn btn-outline-dark fa-solid fa-arrow-left', style:'margin:1rem;'%>
</div>

<div class='text-center'>
  <h1>Items</h1>
</div>
<div class="container" style='width:35rem;'>
  <table class="table" style='margin:auto; width:30rem;'>
  <thead>
    <tr>
      <th scope='col'>Name</th>
      <th scope='col'>Price</th>
      <th scope='col'>Callories</th>
    </tr>
  </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name%></td>
          <td><%= item.price%></td>
          <td><%= item.callories%></td>
          <td><%= link_to "", item, class: 'btn btn-outline-info btn-sm fa-solid fa-eye' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <div style='margin:2rem;'>
  <%= link_to "", new_item_path, class: 'btn btn-outline-secondary btn-sm fa-solid fa-plus' %>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>New item</h1>

  <%= render "formnew", item: @item %>

  <br>

  <div>
    <%= link_to "Back to items", items_path, class: 'btn btn-outline-primary btn-sm' %>
  </div>
</div>

app/views/items/show.html.erb
<div style='margin-left: 3rem; margin-top:1rem;'>
  <%= link_to "", items_path, class: "btn btn-outline-dark fa-solid fa-arrow-left" %>
  </div>

  <%= render @item %>

  <div>
    <br>
    <button id='restaurants' class='btn btn-outline-dark' onclick='showRestaurants(event)' style='margin-left:4rem;'>Show Restaurants</button>

    <br> <br>
    <% if can? :manage, Item %>
      <%= link_to "", edit_restaurant_item_path(@item.restaurant_id, @item), class: 'btn btn-outline-warning fa-solid fa-pencil', style: 'margin-left:3rem;' %>
    <% end %>
    <br><br>
    <% if can? :manage, Item %>
      <%= button_to "", @item, method: :delete , class: "btn btn-outline-danger fa-solid fa-trash", style: 'margin-left:3rem;'%>
    <% end %>
  </div>
</div>


<script>
  function showRestaurants(event){
    event.preventDefault();
    let restaurants = document.getElementById('restaurants');
  }
</script>